tutorialsIndex_es = {"I. Professiones", "II. Ancestral System", "III. Mazmorras", "IV. Sistemas"}

tutorialsInfo_es = {
    {
        {name = "01. Mining", text = "Minner's Forge esta ubicada al sur de Mordragor, encontraran el Npc Elyotrope, Elyotrope vende la primera pickaxe para empezar a minar. Pueden comprarla y empezar desde ahora a colectar minerales, transformarlos en la Forja de mineros y venderlos a Elyotrope para obtener dinero.", img = "imgs/minners_forge"}, 
		{name = "02. Woodcutting", text = "Woodcutter's Forge está ubicada en la salida suroeste de Falanaar, aquí encontrarás al npc Rostock, él vende la primera hacha para comenzar a cortar árboles en todo el mundo. La compró, recolecta madera y elabora artesanías. algunas tablas y venderlas a Rostock.", img = "imgs/woodcutting_craft"}, 
        {name = "03. Herbalist", text = "Herbalist's Forge está ubicada al norte de Dolwatha, aquí encontrarás al npc Elyria, ella vende las primeras tijeras para comenzar a cosechar plantas en todo el mundo. Lo compré, recolecté plantas y hongos y luego elaboré pociones. Las pociones son útiles, véndelas en el mercado o úsalas para ayudarte en las batallas.", img = "imgs/herbalist_craft"}, 
 },
    {
        {name = "01. Ancestral System", text = "El Sistema Ancestral se basa en Tasks, completa Tasks con el npc Armin disponible en cada ciudad, por ejemplo en Mordragor en el último piso del depósito, y gana Puntos Ancestrales para gastar en la Tienda Ancestral, pero también Puntos de Rango Ancestral para aumentar tu Clasificación Ancestral. ¡Puedes verificar tu estado en Ancestral System usando el comando !ancestral verás tu Clasificación, Puntos y Tareas que has aceptado, estados actuales de tasks, etc.\nArriba derecha en el cliente, encontraran una imagen de un cofre, que corresponde a la tienda Ancestral en la cual podran comprar wings, auras y otras cosas.", img = "imgs/armin_npc"},
    },	
    {
        {name = "01. Mazmorras", text = "Mazmorras, introdujimos un sistema de mazmorras, donde lucharás contra criaturas pero también contra un jefe. Forma tu propio equipo y derrota a los jefes. La mazmorra se puede iniciar en el Templo de Mordragor, ubicado en el Dungeon Teleporter..", img = "imgs/dungeons"},
        {name = "02. Bones Dungeon", text = "Bones Dungeon Requiere un equipo de 2 jugadores y un nivel mínimo de 150, tendrás 30 minutos para derrotar a las criaturas y llegar al jefe llamado Prince Skeletal.", img = "imgs/dungeon_bones"},
        {name = "03. Master of the Elements", text = "Master of the Elements introduce un sistema de niveles, que se explica en Otros sistemas. La mazmorra requiere un equipo de 2 jugadores, nivel 200 mínimo, encontrarás criaturas y jefes.", img = "imgs/masterlements"},
    },	
    {
        {name = "01. Tier System", text = "El sistema de niveles se basa en equipos personalizados, que te permiten usar una piedra con incrustaciones de estrellas para insertar 3 estrellas vacías en el equipo. Una vez que hayas insertado 3 estrellas vacías, puedes insertar una piedra estelar siguiendo la rareza:\n- Común (verde)\n- Raro (azul)\n- Muy raro (oro)\n- Épico (púrpura)\n- Legendario (rojo)\nCada nivel tiene 1, 2 o 3 estrellas.\n\nLa primera estrella tomará las estadísticas base de la actualización anterior (significa 1 estrella, no se incrementan las estadísticas primarias o secundarias)\nLa segunda estrella se incrementará estadísticas secundarias (resistencia, velocidad, etc.)\nThirst Star incrementará las primeras estadísticas (habilidades: hacha, distancia..., armadura...)\nPara comenzar a agregar un nivel a un equipo personalizado, primero debes derrotar al Maestro de los Elementos. y obtén Star Inlay Stone, usándola en el equipo permitido (Netherwave, Skeletal, Varruth, Seetheras o Felsinger), casco, armadura, piernas y botas, solo podrás comenzar a incrustar una piedra, prueba tu oportunidad para obtener lo mejor. Incrusta piedra para aumentar tus estadísticas.\nDespués de agregar una piedra, por ejemplo 2 estrellas azules (raras), a un equipo y saquearás, por ejemplo, una épica o legendaria, y deseas agregarla a tu equipo, necesitarás usar estrella. Extractor en tu equipo para poder extraer la piedra incrustada en tu equipo, tu objeto volverá a tener 3 estrellas vacías y podrás insertar una nueva. Recibirás la piedra incrustada en el equipo después de extraerla, pero perderás el extractor de estrellas.", img = "imgs/tiers"},
		{name = "02. Azure Portales", text = "Los Portales Azure son portales aleatorios que aparecen en Freewind, Dolwatha, Death Valley y Rivendell (Arkeron).\nAntes de ingresar, puedes encontrar un nuevo NPC llamado Estherya que ella intercambia. Las Nightmare Coins se obtienen matando jefes o completando tareas en tareas ancestrales, que ella vende. Trajes.\nEl interior es muy grande, necesitas encontrar al jefe llamado Azure y derrotarlo, ganarás Monedas Azure que se pueden usar en la Entrada Azure y obtendrás una recompensa, nuevas piezas de cosas que pueden incrustar nuevas estrellas y llegar a los poderosos. de los nuevos conjuntos.\nHay 4 conjuntos nuevos, Netherwave (hechiceros y druidas), Varruth y Seetheras (para Caballero), ambos son iguales, pero visuales diferentes y Felsinger (paladines). Intercambia Azure Coins por Taerar Npc en la entrada de Azure Portals.", img = "imgs/estherya"},
		{name = "03. Extensiones", text = "Hay mucho contenido personalizado, pero también contenido que conoces hasta ahora y que es genial encontrar aquí:\nBiblioteca secreta, acceso: Mordragor norte (campamento bárbaro), nivel: 250+\nBastión Falcon, acceso: Falanaar norte (terrenos profundos) , Nivel: 200+\nBastión Cobra, Acceso: Dolwatha Norte (cerca de la aparición del Portal Azure), Nivel: 200+\n Jefes de peligro grave, Acceso: Cueva subterránea de la muerte de Mordragor, Nivel: 200+\n Espectros Bruster, Leones, Desierto profundo , Acceso: Desde cualquier barco a Kilmaresh (norte de Kilmaresh), Nivel: 160+\n Bounac, Acceso: Desde cualquier barco, Nivel: 220+\n Soul War, Acceso: Desde cualquier barco a Kilmaresh (Central Top Mountain), Nivel : 300+\n Kilmaresh, Urmahlullu's, Acceso: desde cualquier barco hasta Kilmaresh Central bajo Kilmaresh, Nivel: 250+\n Rotten Blood, Acceso: Desde cualquier barco hasta Kilmaresh (South Kilmaresh, Portal), Nivel: 300+.", img = "imgs/bakragore"},		
		{name = "04. Badges", text = "Los Badges son equipos nuevos que se pueden equipar en una nueva ranura. Los Badges se pueden mejorar con amplificadores para alcanzar el último nivel, cada badge es diferente.\nLas insignias se obtienen matando World Bosses, consulte la categoría Las Islas.", img = "imgs/badges"},	
		{name = "05. Deck System", text = "Deck System es un nuevo sistema que permite al jugador equipar un mazo, puede agregar cartas en su mazo y activarlo para obtener bonificación o cambiar elementos de hechizos.\nHay cartas normales y cartas legendarias, como los deck's (bronce, plata y oro) son loot de los World Bosses en Las Islas.", img = "imgs/deck"},	
		{name = "06. Boat System", text = "¡Empiece a navegar por el continente y explore nuevas islas, nuevos monstruos, luche contra increíbles jefes del mundo y mucho más!\nPara comenzar a navegar, hable con Magnus Blackwater en el puerto de los muelles (disponible en cada ciudad), conozca al comerciante Shipwright que recolecta piezas de barcos.\nEl océano es peligroso , presta atención por donde vas, algunos piratas andan rondando las mercancías en las aguas, tengan cuidado!.", img = "imgs/boat"},	
		{name = "07. The Isles", text = "Hay 9 nuevas islas alrededor del mundo, donde puedes encontrar en cada isla nuevos monstruos y Worldbosses. Los World Bosses aparecen en una hora determinada de la semana, presta atención al tiempo de reaparición, encuentra jugadores y derrótalos para recolectar cartas, deck, badges, equipos y mejorar recursos.", img = "imgs/worldbosses"},
	
	},			
}