tutorialsIndex_en = {"I. Professions", "II. Ancestral System", "III. Dungeons", "IV. Systems"}

tutorialsInfo_en = {
    {
        {name = "01. Mining", text = "Minner's Forge is located at south of Mordragor, here you will find npc Elyotrope, Elyotrope Sells the first pickaxe to start mining. Bought it, collect pieces , craft small and big ingots and sell it to Elyotrope to earn money.", img = "imgs/minners_forge"}, 
		{name = "02. Woodcutting", text = "Woodcutter's Forge is located at the south west exit of Falanaar, here you will find npc Rostock he sells the first axe for start cutting tree's around the world. Bought it, collect wood , craft some planks and sell it to Rostock.", img = "imgs/woodcutting_craft"}, 
        {name = "03. Herbalist", text = "Herbalist's Forge is located at the norht of Dolwatha, here you will find npc Elyria she sells the first scissor's for start harvesting plant's around the world. Bought it, collect plants and mushrooms then craft potions. Potions are useful, sell it on the market or use it to help you on battle's.", img = "imgs/herbalist_craft"}, 	
 },
    {
        {name = "01. Ancestral System", text = "Ancestral System is based on tasks, complete tasks with npc Armin available on each city, for example on Mordragor on the last floor of depot, and earn Ancestral Points to spend on Ancestral Store, but also Ancestral Rank Points to grow your Ancestral Ranking.\nYou can check your status on Ancestral System using the command !Ancestral you will see your Ranking, Points, and Tasks that you have accepted, current statuts, etc.\nUp right in the client, you will find an image of a chest, which corresponds to the Ancestral store where you can buy wings, auras and other things by completing tasks.", img = "imgs/armin_npc"},
    },	
    {
        {name = "01. Dungeon", text = "Dungeons we introduced a dungeon system, where you will fight creatures but also a Boss. Make your own team and go defeat the bosses. The dungeon can be started on Temple of Mordragor stading on the Dungeon Teleporter.", img = "imgs/dungeons"},
        {name = "02. Bones Dungeon", text = "Bones Dungeon Requires a team of 2 players and level 150 minimum, you will get 30 minuts to defeat creatures and reach the boss called Prince Skeletal.", img = "imgs/dungeon_bones"},
        {name = "03. Master of the Elements", text = "Master of the Elements introduces a Tier System, that is explained on Others Systems. The dungeon requires a team of 2 players, level 200 minimum, you will find creatures and Boss.", img = "imgs/masterlements"},
    },	
    {
        {name = "01. Tier System", text = "Tier System is based on custom equipments, that allows you to use an Star Inlay Stone in order to insert 3 empty stars to the equipment. Once you have inserted 3 Empty stars, you can insert a star stone following the rarity:\n- Common (green)\n- Rare (blue)\n- Very Rare (gold)\n- Epic (purple)\n- Legendary (red)\nEach Tier, has 1, 2 or 3 Stars.\n\nFirst Star, will take the base stats of the previous upgrade ( it means 1 star, no primary or secundary stats are incremented )\nSecond Star will increment secundary stats ( Resistance, Speed, Etc )\nThirst Star will increment first stats (Skills: Axe, distance..., Armor...)\nTo start adding a tier to a custom equipment, first you need defeat Master of The Elements and obtain Star Inlay Stone, using it on allowed equipment ( Netherwave, Skeletal, Varruth, Seetheras or Felsinger ) , Helmet, Armor, Legs and Boots only you will be able to start inlay a stone, try your chance in order to get the best Inlay Stone to increase your stats.\nAfter adding a stone, for example 2 Blue Stars ( Rare ), to an equipment and you will loot for example an Epic or Legendary, and you wish add it to your equipment, you will need use Star Extractor on your equipment in order to extract the stone incrusted to your equipment, your item will become again with 3 Empty stars and able to insert the new one. You will receive the stone incrusted to the equipment after extract it, but you will lose the star extractor.", img = "imgs/tiers"},
		{name = "02. Azure Portals", text = "Azure Portals are random portals appearing on Freewind, Dolwatha, Death Valley and Rivendell (Arkeron).\nBefore enter, you can find a new Npc called Estherya she trade , Nightmare Coins are obtained by killing Bosses or completing Tasks on Ancestral Tasks, she sells Outfits.\nInside is very big, you need find the boss called Azure and defeat it, you will earn Azure Coins that can be used at the Azure Entrance and get a reward, new pieces of stuff that can inlay new stars and reach the powerful of the new sets.\nThere is 4 new sets, Netherwave ( sorcerers & druids ), Varruth & Seetheras ( for Knight ) both are same, but visual differently and Felsinger ( paladins ). Exchange Azure Coins to Taerar Npc at the entrance of Azure Portals.", img = "imgs/estherya"},
		{name = "03. Expansion Maps", text = "There is much custom content, but also content that you know so far that are great to find here:\nSecret Library, Acess: North Mordragor (Barbarian Camp), Level: 250+\nFalcon Bastion, Acess: North Falanaar (Deepling Grounds), Level: 200+\nCobra Bastion, Acess: North Dolwatha (Near Azure Portal Apparition), Level: 200+\n Grave Danger Bosses, Acess: Underground Mordragor Death Cave, Level: 200+\n Bruster Spectres, Lions, Deep Desert, Acess: From any Boat to Kilmaresh (north Kilmaresh), Level: 160+\n Bounac, Acess: From any Boat, Level: 220+\n Soul War, Acess: From any Boat to Kilmaresh (Central Top Mountain), Level: 300+\n Kilmaresh, Urmahlullu's, Acess: From any Boat to Kilmaresh Central Under Kilmaresh, Level: 250+\n Rotten Blood, Acess: From any Boat to Kilmaresh (South Kilmaresh, Portal), Level: 300+.", img = "imgs/bakragore"},	
		{name = "04. Badges", text = "Badges are new equipment that can be equipped on a new slot. Badges can be upgraded with amplifiers to reach the last tier, each badge is differently.\nBadges are obtained by killing world bosses, see category The Isles.", img = "imgs/badges"},	
		{name = "05. Deck System", text = "Deck System is a new system that allows player to Equip a Deck, you can add cards on your deck and activate it in order to obtain bonus or change elements of spells.\nThere are normal cards and legendary cards, like deck's (bronze, silver and gold) are looted from World Bosses on The Isles.", img = "imgs/deck"},	
		{name = "06. Boat System", text = "Start navigating around continent and explore new Isles, new monsters, fight Incredible Worldbosses and much more!\nTo start navigating talk with Magnus Blackwater on the docks port (available on each city), meet Shipwright trader who collects boat parts.\nOcean is dangereous, pay attention where you go, some pirates are around tho thief merchandises.", img = "imgs/boat"},	
		{name = "07. The Isles", text = "There is 9 new isles around the world, where you can find on each isle, new monsters and Worldbosses. Worldbosses appear on a determinated hour on the week, pay attention about the respawn time, find players and defeat them to collect cards, deck, badges, equipment and upgrade ressources.", img = "imgs/worldbosses"},	
    
	},			
}