tutorialsIndex_pt = {"I. Profissoes", "II. Ancestral System", "III. Masmorras", "IV. Sistemas"}

tutorialsInfo_pt = {
    {
        {name = "01. Mineracao", text = "Minner's Forge esta localizada ao sul de Mordragor, voce encontrara o Npc Elyotrope, Elyotrope vende a primeira picareta para iniciar a mineracao. Voce pode compra-lo e comecar a coletar minerais agora, transforma-los na Forja dos Mineiros e vende-los ao Elyotrope para conseguir dinheiro.", img = "imgs/minners_forge"}, 
		{name = "02. Xilogravura", text = "A Forja do Lenhador esta localizada na saida sudoeste de Falanaar, aqui voce encontrara o npc Rostock, ele vende o primeiro machado para comecar a derrubar arvores ao redor do mundo. Ele comprou, coleta madeira e faz artesanato. algumas pranchas e vende-las para Rostock.", img = "imgs/woodcutting_craft"}, 
        {name = "03. Herbalista", text = "A Herbalist's Forge esta localizada ao norte de Dolwatha, aqui voce encontrara a npc Elyria, ela vende as primeiras tesouras para comecar a colher plantas ao redor do mundo. Comprei, coletei plantas e cogumelos e depois preparei pocoes. Pocoes sao uteis, venda-as no mercado ou use-as para ajuda-lo nas batalhas.", img = "imgs/herbalist_craft"}, 
 },
    {
        {name = "01. Ancestral System", text = "O Sistema Ancestral e baseado em Tarefas, complete Tarefas com o npc Armin disponivel em cada cidade, por exemplo em Mordragor no ultimo andar do armazem, e ganhe Pontos Ancestrais para gastar na Loja Ancestral, mas tambem Pontos de Classificacao Ancestral para aumentar seu Classificacao Ancestral. Voce pode verificar seu status no Sistema Ancestral usando o comando !ancestral voce vera sua Classificacao, Pontos e Tarefas que voce aceitou, status atual das tarefas, etc.\nNo canto superior direito do cliente, voce encontrara a imagem de um bau, que corresponde a loja Ancestral onde voce pode comprar asas, auras e outras coisas.", img = "imgs/armin_npc"},
    },	
    {
        {name = "01. Masmorras", text = "Masmorras, introduzimos um sistema de masmorras, onde voce lutara contra criaturas, mas tambem contra um chefe. Forme sua propria equipe e derrote os chefes. A masmorra pode ser iniciada no Templo de Mordragor, localizado no Dungeon Teleporter.", img = "imgs/dungeons"},
        {name = "02. Masmorra Bones", text = "Bones Dungeon Requer uma equipe de 2 jogadores e nivel minimo de 150, voce tera 30 minutos para derrotar as criaturas e chegar ao chefe chamado Prince Skeletal.", img = "imgs/dungeon_bones"},
        {name = "03. Master of the Elements", text = "Master of the Elements apresenta um sistema de nivelamento, que e explicado em Outros Sistemas. A masmorra requer uma equipe de 2 jogadores, nivel minimo 200, voce encontrara criaturas e chefes.", img = "imgs/masterlements"},
    },	
    {
        {name = "01. Tier System", text = "O sistema de nivelamento e baseado em equipamentos customizados, que permitem usar uma pedra incrustada de estrelas para inserir 3 estrelas vazias no equipamento. Depois de inserir 3 estrelas vazias, voce pode inserir uma pedra estrela seguindo a raridade:\n- Comum (verde)\n- Raro (azul)\n- Muito raro (ouro)\n- Epico (roxo)\n- Lendario (vermelho)\nCada nivel tem 1, 2 ou 3 estrelas.\n\nA primeira estrela usara as estatisticas basicas da atualizacao anterior (significa 1 estrela, sem aumento de estatisticas primarias ou secundarias)\nA segunda estrela aumentara as estatisticas secundarias (resistencia, velocidade, etc.)\nThirst Star aumentara as primeiras estatisticas (habilidades: machado, distancia..., armadura...)\nPara comecar a adicionar um nivel a um equipamento personalizado, voce deve primeiro derrotar o Mestre do Elementos e consiga Star Inlay Stone, usando-a nos equipamentos permitidos (Netherwave, Skeletal, Varruth, Seetheras ou Felsinger), capacete, armadura, pernas e botas, voce so podera comecar a embutir uma pedra, tente a sua chance de conseguir a melhor . Incorpore uma pedra para aumentar suas estatisticas.\nDepois de adicionar uma pedra, por exemplo 2 estrelas azuis (raras), a um equipamento e saquear, por exemplo, um epico ou lendario, e desejar adiciona-la ao seu equipamento, voce ira precisa usar estrela. Extrator em seu equipamento para poder extrair a pedra embutida em seu equipamento, seu objeto voltara a ter 3 estrelas vazias e voce podera inserir uma nova. Voce recebera a pedra embutida no equipamento apos extrai-la, mas perdera o extrator de estrelas.", img = "imgs/tiers"},
		{name = "02. Portais do Azure", text = "Os Portais Azure são portais aleatorios que aparecem em Freewind, Dolwatha, Death Valley e Rivendell (Arkeron).\nAntes de entrar, voce pode encontrar um novo NPC chamado Estherya que ela negocia. As Moedas do Pesadelo são obtidas matando chefes ou completando tarefas em tarefas antigas, que ela vende. Ternos.\nO interior e muito grande, voce precisa encontrar o chefe chamado Azure e derrota-lo, voce ganhara Azure Coins que poderão ser usadas na Entrada do Azure e recebera uma recompensa, novas pecas de coisas que podem incorporar novas estrelas e alcancar os poderosos. dos novos conjuntos.\nExistem 4 novos conjuntos, Netherwave (feiticeiros e druidas), Varruth e Seetheras (para Knight), ambos iguais, mas com visuais diferentes e Felsinger (paladinos). Troque Azure Coins por Taerar Npc na entrada dos Portais Azure.", img = "imgs/estherya"},
		{name = "03. Extensões", text = "Ha muito conteudo personalizado, mas tambem conteudo que voce conhece ate agora e que e otimo encontrar aqui:\nBiblioteca Secreta, Acesso: North Mordragor (Acampamento Barbaro), Nivel: 250+\nFalcon Hold, Acesso: North Falanaar (Deep Grounds ), Nivel: 200+\nCobra Bastion, Acesso: North Dolwatha (perto da aparencia do Portal Azure), Nivel: 200+\n Grave Danger Bosses, Acesso: Caverna Subterrânea da Morte de Mordragor, Nivel: 200+\n Bruster Wraiths , Lions, Deep Desert, Acesso: De qualquer navio para Kilmaresh (norte de Kilmaresh), Nivel: 160+\n Bounac, Acesso: De qualquer navio, Nivel: 220+\n Soul War, Acesso: De qualquer navio para Kilmaresh (Central Top Mountain), Nivel: 300+\n Kilmaresh, Urmahlullu's, Acesso: de qualquer navio para Kilmaresh Central Abaixo de Kilmaresh, Nivel: 250+\n Rotten Blood, Acesso: De qualquer navio para Kilmaresh (South Kilmaresh, Portal), Nivel: 300+.", img = "imgs/bakragore"},		
		{name = "04. Badges", text = "Os emblemas são novos equipamentos que podem ser equipados em um novo slot. Os emblemas podem ser atualizados com amplificadores para atingir o ultimo nivel, cada emblema e diferente.\nOs emblemas são obtidos matando Chefes Mundiais, consulte a categoria As Ilhas.", img = "imgs/badges"},	
		{name = "05. Deck System", text = "Deck System e um novo sistema que permite ao jogador equipar um deck, ele pode adicionar cartas ao seu deck e ativa-lo para obter bônus ou alterar elementos de feitico.\nExistem cartas normais e cartas lendarias, como as do deck (bronze, prata e ouro) são saques dos Chefes Mundiais nas Ilhas.", img = "imgs/deck"},	
		{name = "06. Sistema de barco", text = "Comece a navegar pelo continente e explore novas ilhas, novos monstros, lute contra chefes mundiais incriveis e muito mais!\nPara comecar a navegar, fale com Magnus Blackwater no porto (disponivel em todas as cidades), conheca o comerciante Shipwright que coleta pecas de navios. \nO oceano e perigoso, preste atencão por onde voce vai, alguns piratas estão rondando as mercadorias nas aguas, tome cuidado!", img = "imgs/boat"},	
		{name = "07. As Ilhas", text = "Existem 9 novas ilhas ao redor do mundo, onde voce pode encontrar novos monstros e Worldbosses em cada ilha. Os Chefes Mundiais aparecem em um determinado horario da semana, preste atencão no tempo de respawn, encontre jogadores e derrote-os para coletar cartas, baralho, insignias, equipamentos e melhorar recursos.", img = "imgs/worldbosses"},
	
	},			
}